version: "3"
services:

  mne:
    image: caldweba/mne-docker
    environment:
      XAUTHORITY: "/.Xauthority"
      DISPLAY: "host.docker.internal:0"
    volumes:
      - "$HOME/.Xauthority:/.Xauthority"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "./shared:/home/mne_user/shared"
