version: "3"
services:

  mne:
    image: caldweba/mne-docker
    environment:
      DISPLAY: ":0"
    volumes:
      - "./shared:/home/mne_user/shared"
    ports:
      - "8888:8888"
    command: "/home/mne_user/miniconda/envs/mne/bin/jupyter notebook"
